### ISSUE TITLE
User interface for active learning

### ISSUE THREAD

**Issue by Dumbris** [rmunro/pytorch_active_learning#2]
I would like to share the way how to speed up the annotation process and make it more comfortable. I slightly modified get_annotation function in your example https://github.com/Dumbris/pytorch_active_learning/blob/fb01780cc45de71fa2476db7b3ece3e333768ab4/active_learning_basics.py#L127

For UI I am using my library https://github.com/Dumbris/trunklucator
You can install it with `pip install trunklucator`

Thank you, looking forward to the book release!

**Comment by rmunro** [comment]
What a great UI! I'm about to start writing the chapter on user-interfaces for annotation. I'll look into trunklucator. I hadn't seen it before!

**Comment by rmunro** [comment]
I ended up using something similar in the most recent chapter, eel. Thanks again for the interesting extension to this work!
