### ISSUE TITLE
Anything We can Contribute to this Repo?

### ISSUE THREAD

**Issue by riven314** [rmunro/pytorch_active_learning#4]
Thanks for such an amazing repo! This is by far the most comprehensive tutorials on active learning I have found. (most importantly, it is written in PyTorch)
Is there any way I can help contribute to this repo? Glad to make this repo even better!

**Comment by rmunro** [comment]
Thank you! You are welcome to contribute anything that you'd like! There are some popular methods using Monte Carlo Sampling (Bayesian Deep Learning) that are not yet part of the repo. They would be an interesting addition. It is probably a few dozen lines of extra code to include dropouts and process the results, but it might be tricky to get it exactly right and working!

**Comment by riven314** [comment]
got it! Iet me review that first.
