### ISSUE TITLE
A mistake about high_uncertainty_cluster

### ISSUE THREAD

**Issue by freshbirdDD** [rmunro/pytorch_active_learning#7]
On page 151 of 《Human-in-the-Loop-Machine-learning》, the code shows:
“”“
for key in item_keys:
	...
    score = method(prob_dist.data[0]) # get the specific type of uncertainty sampling
	total_uncertainty += 1.0
	count += 1
average_uncertainty = total_uncertainty / count #B
”“”
It should be 'total_uncertainty += score',  not 'total_uncertainty += 1.0', otherwise the average uncertainty will be constant 1.0.

**Comment by rmunro** [comment]
Thanks for picking this up! It was a mistake both in the book and this code.
